apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: demo-app-cluster-role
rules:
  - apiGroups: ["shift-week.example.com"]
    resources: ["noteconfigs"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: demo-app-cluster-rolebinding
subjects:
  - kind: ServiceAccount
    name: demo-app
    namespace: shift-week-demo
roleRef:
  kind: ClusterRole
  name: demo-app-cluster-role
  apiGroup: rbac.authorization.k8s.io
