apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-app-data
  namespace: shift-week-demo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: topolvm-provisioner
  resources:
    requests:
      storage: 1Gi
